/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/YGEnums.h>
#include <yoga/enums/YogaEnums.h>

namespace facebookyg::yoga {

enum class Edge : uint8_t {
  Left = FBYGEdgeLeft,
  Top = FBYGEdgeTop,
  Right = FBYGEdgeRight,
  Bottom = FBYGEdgeBottom,
  Start = FBYGEdgeStart,
  End = FBYGEdgeEnd,
  Horizontal = FBYGEdgeHorizontal,
  Vertical = FBYGEdgeVertical,
  All = FBYGEdgeAll,
};

template <>
constexpr int32_t ordinalCount<Edge>() {
  return 9;
}

constexpr Edge scopedEnum(FBYGEdge unscoped) {
  return static_cast<Edge>(unscoped);
}

constexpr FBYGEdge unscopedEnum(Edge scoped) {
  return static_cast<FBYGEdge>(scoped);
}

inline const char* toString(Edge e) {
  return FBYGEdgeToString(unscopedEnum(e));
}

} // namespace facebookyg::yoga
