/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/YGEnums.h>
#include <yoga/enums/YogaEnums.h>

namespace facebookyg::yoga {

enum class Errata : uint32_t {
  None = FBYGErrataNone,
  StretchFlexBasis = FBYGErrataStretchFlexBasis,
  AbsolutePositionWithoutInsetsExcludesPadding = FBYGErrataAbsolutePositionWithoutInsetsExcludesPadding,
  AbsolutePercentAgainstInnerSize = FBYGErrataAbsolutePercentAgainstInnerSize,
  All = FBYGErrataAll,
  Classic = FBYGErrataClassic,
};

FBYG_DEFINE_ENUM_FLAG_OPERATORS(Errata)

constexpr Errata scopedEnum(FBYGErrata unscoped) {
  return static_cast<Errata>(unscoped);
}

constexpr FBYGErrata unscopedEnum(Errata scoped) {
  return static_cast<FBYGErrata>(scoped);
}

inline const char* toString(Errata e) {
  return FBYGErrataToString(unscopedEnum(e));
}

} // namespace facebookyg::yoga
