/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/YGEnums.h>
#include <yoga/enums/YogaEnums.h>

namespace facebookyg::yoga {

enum class FlexDirection : uint8_t {
  Column = FBYGFlexDirectionColumn,
  ColumnReverse = FBYGFlexDirectionColumnReverse,
  Row = FBYGFlexDirectionRow,
  RowReverse = FBYGFlexDirectionRowReverse,
};

template <>
constexpr int32_t ordinalCount<FlexDirection>() {
  return 4;
}

constexpr FlexDirection scopedEnum(FBYGFlexDirection unscoped) {
  return static_cast<FlexDirection>(unscoped);
}

constexpr FBYGFlexDirection unscopedEnum(FlexDirection scoped) {
  return static_cast<FBYGFlexDirection>(scoped);
}

inline const char* toString(FlexDirection e) {
  return FBYGFlexDirectionToString(unscopedEnum(e));
}

} // namespace facebookyg::yoga
