/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/YGEnums.h>
#include <yoga/enums/YogaEnums.h>

namespace facebookyg::yoga {

enum class LogLevel : uint8_t {
  Error = FBYGLogLevelError,
  Warn = FBYGLogLevelWarn,
  Info = FBYGLogLevelInfo,
  Debug = FBYGLogLevelDebug,
  Verbose = FBYGLogLevelVerbose,
  Fatal = FBYGLogLevelFatal,
};

template <>
constexpr int32_t ordinalCount<LogLevel>() {
  return 6;
}

constexpr LogLevel scopedEnum(FBYGLogLevel unscoped) {
  return static_cast<LogLevel>(unscoped);
}

constexpr FBYGLogLevel unscopedEnum(LogLevel scoped) {
  return static_cast<FBYGLogLevel>(scoped);
}

inline const char* toString(LogLevel e) {
  return FBYGLogLevelToString(unscopedEnum(e));
}

} // namespace facebookyg::yoga
