/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <yoga/YGEnums.h>
#include <yoga/enums/YogaEnums.h>

namespace facebookyg::yoga {

enum class Wrap : uint8_t {
  NoWrap = FBYGWrapNoWrap,
  Wrap = FBYGWrapWrap,
  WrapReverse = FBYGWrapWrapReverse,
};

template <>
constexpr int32_t ordinalCount<Wrap>() {
  return 3;
}

constexpr Wrap scopedEnum(FBYGWrap unscoped) {
  return static_cast<Wrap>(unscoped);
}

constexpr FBYGWrap unscopedEnum(Wrap scoped) {
  return static_cast<FBYGWrap>(scoped);
}

inline const char* toString(Wrap e) {
  return FBYGWrapToString(unscopedEnum(e));
}

} // namespace facebookyg::yoga
